#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shadowsocksr[-1]
	add ucitrack shadowsocksr
	set ucitrack.@shadowsocksr[-1].init=shadowsocksr
	commit ucitrack
	delete firewall.shadowsocksr
	set firewall.shadowsocksr=include
	set firewall.shadowsocksr.type=script
	set firewall.shadowsocksr.path=/var/etc/shadowsocksr.include
	set firewall.shadowsocksr.reload=1
	commit firewall
EOF

rm -rf /etc/config/shadowsocksr-opkg /etc/ssrplus/*opkg
touch /etc/ssrplus/china_ip.list
touch /etc/ssrplus/deny_domain.list
touch /etc/ssrplus/white_domain.list
touch /etc/ssrplus/block_domain.list
touch /etc/ssrplus/gfw.conf
touch /etc/ssrplus/oversea.conf
touch /etc/ssrplus/ad.conf
touch /etc/config/shadowsocksr
if [ ! -s "/etc/config/shadowsocksr" ]; then
	/etc/init.d/shadowsocksr reset
fi

sed -i "s/option dns_mode '3'/option dns_mode '1'/g" /etc/config/shadowsocksr
sed -i "s/option type 'vmess'"/"option type 'v2ray'\n\toption v2ray_protocol 'vmess'/g" /etc/config/shadowsocksr
sed -i "s/option type 'vless'"/"option type 'v2ray'\n\toption v2ray_protocol 'vless'/g" /etc/config/shadowsocksr

if [ -s "/etc/uwsgi/vassals/luci-webui.ini" ]; then
	limit=$(cat /etc/uwsgi/vassals/luci-webui.ini | grep -Eo "limit-as.*" | grep -Eo "[0-9]+")
	[ $limit -lt 5000 ] && sed -i '/limit-as/c\limit-as = 5000' /etc/uwsgi/vassals/luci-webui.ini &&
		/etc/init.d/uwsgi restart
fi
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache
exit 0
